<!-- Generated by @canonical/summon-component:svelte v0.1.0 -->

<script lang="ts" module>
  import { defineMeta } from "@storybook/addon-svelte-csf";
  import SkipLink from "./SkipLink.svelte";

  const { Story } = defineMeta({
    title: "Components/SkipLink",
    component: SkipLink,
    tags: ["autodocs"],
    parameters: {
      // Svelte 5 Storybook autodocs do not currently pick up component docs from
      // the component source reliably, so we inject the description here instead:
      // https://github.com/storybookjs/storybook/discussions/34104#discussioncomment-16084065
      docs: {
        description: {
          component:
            "The `SkipLink` component provides a way for users to quickly navigate to the main content of a page.\n\nIt is typically used by keyboard and screen reader users to bypass repetitive navigation links and other elements that appear at the top of the page, pursuant to [WCAG 2.1 Success Criterion 2.4.1](https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks.html).\n\n`SkipLink` should be placed near the top of your document body, before the `<main>` element. The `<main>` element should have a `tabindex` of `-1` to prevent it from receiving focus from the keyboard without using the skip link.",
        },
      },
      // SkipLink is hidden by default until focused, so snapshots are disabled by default.
      chromatic: {
        disableSnapshot: true,
      },
    },
  });
</script>

<Story name="Default" asChild>
	<SkipLink />
	<main id="main" tabindex="-1">
		<p>
			Click inside this example box, then press Tab to focus the skip
			link.
		</p>
		<!-- biome-ignore lint/a11y/useValidAnchor: for demo only -->
		<a href="#">After skipping to main content, this is next in focus order</a>
	</main>
</Story>

<Story
	name="CustomMainElement"
	args={{
		mainId: "my-main-element",
	}}
	parameters={{
		docs: {
			description: {
				story:
					'If your `<main>` element\'s ID is not `"main"`, use the `mainId` prop to specify the correct ID.',
			},
		},
	}}
	asChild
>
	<SkipLink mainId="my-main-element">Skip to custom main element</SkipLink>
	<main id="my-main-element" tabindex="-1">
		<p>
			Click inside this example box, then press Tab to focus the skip
			link.
		</p>
		<!-- biome-ignore lint/a11y/useValidAnchor: for demo only -->
		<a href="#">After skipping to main content, this is next in focus order</a>
	</main>
</Story>

<Story
	name="CustomText"
	parameters={{
		docs: {
			description: {
				story:
					'The skip link\'s contents, by default, are `"Skip to main content"`. You can customize this by passing in your own children.',
			},
		},
	}}
	asChild
>
	<SkipLink>Custom skip text</SkipLink>
	<main id="main" tabindex="-1">
		<p>
			Click inside this example box, then press Tab to focus the skip
			link.
		</p>
		<!-- biome-ignore lint/a11y/useValidAnchor: for demo only -->
		<a href="#">After skipping to main content, this is next in focus order</a>
	</main>
</Story>

<Story name="Focused" tags={["!dev", "!autodocs"]} asChild>
	<div class="story-force-focused">
		<SkipLink />
	</div>
	<main id="main" tabindex="-1">
		<p>Forced-visible style variant for visual checks.</p>
	</main>
</Story>

<Story name="FocusedRtl" tags={["!dev", "!autodocs"]} asChild>
	<div class="story-force-focused" dir="rtl">
		<SkipLink />
	</div>
	<main id="main" tabindex="-1" dir="rtl">
		<p>Forced-visible RTL style variant for visual checks.</p>
	</main>
</Story>

<style>
	.story-force-focused :global(.skip-link) {
		inset-inline-start: var(--space-100, 0.5rem) !important;
		outline-offset: calc(-1 * var(--dimension-stroke-thickness-large, 3px)) !important;
		padding-block: var(--space-200, 1rem) !important;
		padding-inline: var(--space-200, 1rem) !important;
		position: fixed !important;
		top: var(--space-100, 0.5rem) !important;
		z-index: 999999 !important;
	}
</style>

