<!-- Generated by @canonical/summon-component:svelte v0.1.0 -->

<script lang="ts">
  import type { SkipLinkProps } from "./types.js";
  import "./styles.css";

  const componentCssClassName = "ds skip-link";

  let {
    class: className,
    children,
    mainId = "main",
    ...rest
  }: SkipLinkProps = $props();

  const href = $derived(`#${mainId}`);
</script>

<a
	class={[componentCssClassName, className]}
	href={href}
	tabindex={0}
	{...rest}
>
	{#if children}
		{@render children()}
	{:else}
		Skip to main content
	{/if}
</a>

<!-- @component
The `SkipLink` component provides a way for users to quickly navigate to the main content of a page.
It is typically used by keyboard and screen reader users to bypass repetitive navigation links
and other elements that appear at the top of the page, pursuant to [WCAG 2.1 Success Criterion 2.4.1](https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks.html).

`SkipLink` should be placed near the top of your document body, before the `<main>` element.
The `<main>` element should have a `tabindex` of `-1` to prevent it from receiving focus from the keyboard without using the skip link.

## Example Usage
```svelte
<SkipLink />
<main id="main" tabindex="-1">
  page content
</main>
```
-->
