// Generated by @canonical/summon-component:svelte v0.1.0

import type { Snippet } from "svelte";
import type { SvelteHTMLElements } from "svelte/elements";

type BaseProps = Omit<SvelteHTMLElements["a"], "href" | "tabindex">;

export interface SkipLinkProps extends BaseProps {
  /** The contents of the skip link itself */
  children?: Snippet;
  /**
   * ID of the main content element.
   * @default "main"
   */
  mainId?: string;
}
