name: Setup environment
description: Installs build tools and dependencies
inputs:
  bun-version:
    default: '1.2.19'
    description: Version of Bun to use
  node-version:
    # we default to 22 (not latest) because versions >= 23 currently cause storybook builds to fail.
    # see https://github.com/canonical/ds25/issues/226, https://github.com/oven-sh/bun/issues/3794
    # TODO we can investigate removing this when Bun supports storybook & we can build without Node
    default: '22'
    description: Version of Node to use
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

      # "prepare" hook on `bun install` runs `bun run build`
    - name: Install dependencies
      shell: bash
      run: bun install #--frozen-lockfile
