import type { Option } from "../ui/Field/types.js";

export const continents: Option[] = [
  { value: "africa", label: "Africa" },
  { value: "antarctica", label: "Antarctica", disabled: true },
  { value: "asia", label: "Asia" },
  { value: "australia", label: "Australia" },
  { value: "europe", label: "Europe" },
  { value: "north_america", label: "North America" },
  { value: "south_america", label: "South America" },
];

export const fruits: Option[] = [
  { value: "apple", label: "Apple" },
  { value: "banana", label: "Banana" },
  { value: "cherry", label: "Cherry" },
  { value: "date", label: "Date" },
  { value: "elderberry", label: "Elderberry" },
  { value: "fig", label: "Fig", disabled: true },
  { value: "grape", label: "Grape" },
  { value: "honeydew", label: "Honeydew" },
  { value: "kiwi", label: "Kiwi", disabled: true },
  { value: "lemon", label: "Lemon" },
  { value: "mango", label: "Mango" },
  { value: "nectarine", label: "Nectarine" },
  { value: "orange", label: "Orange" },
  { value: "papaya", label: "Papaya", disabled: true },
  { value: "quince", label: "Quince" },
  { value: "apricot", label: "Apricot" },
  { value: "avocado", label: "Avocado" },
  { value: "blueberry", label: "Blueberry" },
  { value: "blackberry", label: "Blackberry" },
  { value: "coconut", label: "Coconut" },
  { value: "cranberry", label: "Cranberry" },
  { value: "dragonfruit", label: "Dragonfruit" },
  { value: "feijoa", label: "Feijoa", disabled: true },
  { value: "guava", label: "Guava" },
  { value: "huckleberry", label: "Huckleberry" },
  { value: "kumquat", label: "Kumquat", disabled: true },
  { value: "lime", label: "Lime" },
  { value: "mulberry", label: "Mulberry" },
  { value: "pineapple", label: "Pineapple" },
  { value: "peach", label: "Peach" },
  { value: "raspberry", label: "Raspberry" },
  { value: "strawberry", label: "Strawberry" },
  { value: "tangerine", label: "Tangerine" },
  { value: "watermelon", label: "Watermelon" },
  { value: "yuzu", label: "Yuzu", disabled: true },
  { value: "cantaloupe", label: "Cantaloupe" },
  { value: "grapefruit", label: "Grapefruit" },
  { value: "pear", label: "Pear" },
  { value: "plum", label: "Plum" },
  { value: "pomegranate", label: "Pomegranate", disabled: true },
];
