/* @canonical/generator-ds 0.9.0-experimental.1 */
import type { AllOrNone } from "@canonical/utils";
import type React from "react";
import type {
  FileProps,
  FolderProps,
  SearchBoxProps,
  TreeViewProps,
} from "./common/index.js";

export type BaseNode = {
  name: string;
  // auto-generated by the Node component
  path?: string;
};

export type FileNode = BaseNode & {
  type: "file";
  marker?: React.ReactNode;
};

export type FolderNode = BaseNode & {
  type: "folder";
  children?: Array<FileTreeData>;
};

export type FileTreeData = FolderNode | FileNode;

export type SearchOptions = {
  /**
   * Files and folders to display if matching the search query.
   */
  searchQuery: string;
  /**
   * Callback to update the search query.
   */
  onSearch: (query: string) => void;
};

export type ExpansionOptions = {
  /**
   * Whether the folders are expandible (default is `false`).
   */
  expandable: boolean;
};

export type FileSelectionOptions = {
  /**
   * The currently selected file item.
   */
  selectedFile: FileTreeData | null;
  /**
   * Callback to select a file item.
   */
  onSelectFile: (node: FileTreeData) => void;
};

export type UserContextOptions = AllOrNone<FileSelectionOptions> &
  AllOrNone<SearchOptions> &
  AllOrNone<ExpansionOptions>;
export type ManagedContextOptions = {
  focusNextNode: (direction: "up" | "down") => void;
  focusEndNode: (end: "start" | "end") => void;
  focusNextSiblingCharacter: (character: string) => void;
};
export type ContextOptions = UserContextOptions & ManagedContextOptions;

export type ProviderOptions = {
  /** A unique identifier for the SearchBox */
  id?: string;
  /** Additional CSS classes */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /**
   * Consider using `FileTree.Folder` and `FileTree.File` components to build the file tree.
   */
  children?: React.ReactNode;
  /**
   * The header of the file tree.
   * Consider using `FileTree.Search` component to add search functionality.
   */
  header?: React.ReactNode;
} & UserContextOptions;

export type FileTreeComponent = ((
  props: ProviderOptions,
) => React.ReactElement) & {
  SearchBox: (props: SearchBoxProps) => React.ReactElement | null;
  File: (props: FileProps) => React.ReactElement | null;
  Folder: (props: FolderProps) => React.ReactElement | null;
  TreeView: (props: TreeViewProps) => React.ReactElement | null;
};
