name: "ds-demo-site/chromatic"
on:
  pull_request:
    paths:
      - configs/storybook/**
      - packages/styles/**
      - packages/utils/**
      - packages/react/ds-core/**
      - apps/react/demo/**
  push:
    branches:
      - main
    paths:
      - configs/storybook/**
      - packages/tokens/**
      - packages/styles/**
      - packages/utils/**
      - packages/react/ds-core/**
      - packages/react/ds-app-anbox/**
jobs:
  test-compile:
    uses: ./.github/workflows/chromatic._template.yml
    secrets:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_TOKEN_CANONICAL_DS_DEMO_SITE }}
    with:
      working-directory: apps/react/demo
      externals: '[
        "configs/storybook/**",
        "packages/styles/**",
        "packages/utils/**",
        "packages/react/ds-core/**"
      ]'