name: "Pull request"
on:
  pull_request:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bun-version: ['1.2.15']
        # Add 23, 24, latest once https://github.com/canonical/ds25/issues/226 is closed (Storybook doesn't support >=23 yet)
        node-version: ['20', '21', '22']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup environment for Bun ${{ matrix.bun-version }} and Node ${{ matrix.node-version }}
        uses: ./.github/actions/setup-env
        with:
          bun-version: ${{ matrix.bun-version }}
          node-version: ${{ matrix.node-version }}

      - name: Build all artifacts
        run: lerna run build:all

      - name: Code quality checks
        run: bun run check

      - name: Test
        run: bun run test
  build-gate:
    runs-on: ubuntu-latest
    needs: build-matrix
    if: ${{ success() }}
    steps:
      - name: All checks passed
        run: echo "All build matrix jobs completed successfully"